shellEmulator: true
trustPolicy: no-downgrade
overrides:
  '@nuxt/kit': ^4.4.2
  eslint: ^10.0.3
  magicast: ^0.5.2
  vue-tsc: ^3.0.5
ignoredBuiltDependencies:
  - '@parcel/watcher'
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
